<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d1440ed2-fc35-45b7-9340-bdb9ab6e69d1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Almentor.Domain\Almentor.Domain.csproj" />
    <ProjectReference Include="..\Almentor.Services.Abstraction\Almentor.Services.Abstraction.csproj" />
  </ItemGroup>

</Project>
